theme: minima
title: Mohammed Nabeel's Blog
author: Mohammed Nabeel
email: mohdnabeel13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mohammed Nabeel's awesome new blog site. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: mnabeel # DO NOT include the @ character, or else the build will fail!
github_username:  mnabeelp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
